spring.application.name=hostel

spring.datasource.url=jdbc:mysql://hostel-mysql-hostel.i.aivencloud.com:27031/defaultdb?useSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_k070m-7cgA3HHZN77uQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=8080
server.forward-headers-strategy=framework
